[package]
name = "vmm_vhost"
version = "0.1.0"
keywords = ["vhost", "vhost-user", "virtio", "vdpa"]
description = "a pure rust library for vdpa, vhost and vhost-user"
authors = ["Liu Jiang <gerry@linux.alibaba.com>"]
repository = "https://github.com/rust-vmm/vhost"
documentation = "https://docs.rs/vhost"
readme = "README.md"
license = "Apache-2.0 or BSD-3-Clause"
edition = "2018"

[features]
default = []
vhost-vsock = []
vhost-kern = ["vm-memory"]
vhost-user = []
vhost-user-master = ["vhost-user"]
vhost-user-slave = ["vhost-user"]

[dependencies]
bitflags = ">=1.0.1"
libc = ">=0.2.39"

sys_util = { path = "../../../platform/crosvm/sys_util" } # provided by ebuild
tempfile = { path = "../../../platform/crosvm/tempfile" } # provided by ebuild
vm-memory = { version = "0.2.0", optional = true }

[dev-dependencies]
vm-memory = { version = "0.2.0", features=["backend-mmap"] }
