[package]
name = "audio_streams"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[lib]
path = "src/audio_streams.rs"

[dependencies]
sync = { path = "../../crosvm/sync" } # provided by ebuild
sys_util = { path = "../../crosvm/sys_util" } # provided by ebuild
