[package]
name = "cras_tests"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[dependencies]
audio_streams = { path = "../../../audio_streams" } # provided by ebuild
getopts = "0.2.18"
hound = "3.4.0"
libcras = { path = "../libcras" } # provided by ebuild
sys_util = { path = "../../../../crosvm/sys_util" } # provided by ebuild

[profile.release]
lto = true
panic = 'abort'
overflow-checks = true
