[package]
name = "p9"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[dependencies]
libc = "*"
libchromeos = { path = "../../libchromeos-rs" } # provided by ebuild
wire_format_derive = { path = "wire_format_derive", version = "*" }

[features]
trace = []
