[package]
name = "cros_alsa_derive"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"
description = "Derive macros of cors_alsa."

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "^1"
quote = "^1"
syn = "^1"
